### ISSUE TITLE
Empty repo

### ISSUE THREAD

**Issue by KandBM** [LORER-MTL/MARL_for_fast_timescale_DR#1]
I discovered this repo through the related [Arxiv publication](https://arxiv.org/abs/2301.02593), and this environment could be helpful for my master's thesis studying the cyber security of MARL in building energy systems. When will this repo be populated, or is there someone I could contact to access the environment?

**Comment by MaisonneuvePhilippe** [comment]
The link for this repository has been updated and the project content can now be found at the following link: https://github.com/ALLabMTL/marl-demandresponse
